version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "history"
        versions: ["5.x"]
      - dependency-name: "@types/node"
        versions: ["14.x"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        versions: ["14.x"]
      - dependency-name: "nginx"
        versions: ["1.19.x"]
