version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        versions: [">14"]
      - dependency-name: "history"
        versions: [">4"]
      - dependency-name: "workbox-*"
        versions: [">5"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: [">14"]
      - dependency-name: "nginx"
        versions: [">1.18"]
