name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js v12
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - run: npm test
